import React from 'react';
import { Text } from '@/components/_shared/common';
import { Grid } from '@mui/material';

const EmployeePersonalInformationDetail = () => {
  return (
    <>
      <Grid
        container
        width={700}
        justifyContent='space-between'
        wrap='wrap'
        marginBottom='32px'
      >
        <Grid
          sm={12}
          item
        >
          <Text
            variant='text-lg'
            title='Personal Informaton'
            fontWeight={700}
            color='primary.500'
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Date of Birth'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='07/10/1998'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Gender'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Female'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Martial Status'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Single'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Number of Dependants'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='0'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Nationality'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Indonesia'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Religion'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Islamic'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
      </Grid>
      <Grid
        container
        width={700}
        justifyContent='space-between'
        wrap='wrap'
        marginBottom='32px'
      >
        <Grid
          item
          sm={12}
        >
          <Text
            title='Citizen Address'
            fontWeight={700}
            color='primary.500'
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Country'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Indonesia'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Province'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='DKI Jakarta'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='City'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Jakarta Selatan'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Sub-District'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Kebayoran Baru'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Citizen ID Street Name, Building Name'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Jl. Nipah XV, Jakarta Selatan'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Zip Code'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='88019'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
      </Grid>
      <Grid
        container
        width={700}
        justifyContent='space-between'
        wrap='wrap'
        marginBottom='32px'
      >
        <Grid
          item
          sm={12}
        >
          <Text
            title='Residential Address'
            fontWeight={700}
            color='primary.500'
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Country'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Indonesia'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Province'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='DKI Jakarta'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='City'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Jakarta Selatan'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Sub-District'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Kebayoran Baru'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Citizen ID Street Name, Building Name'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Jl. Nipah XV, Jakarta Selatan'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Zip Code'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='88019'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
      </Grid>
      <Grid
        container
        width={700}
        justifyContent='space-between'
        wrap='wrap'
        marginBottom='32px'
      >
        <Grid
          item
          sm={12}
        >
          <Text
            title='Personal ID'
            fontWeight={700}
            color='primary.500'
            variant='text-lg'
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='ID Type'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='KTP'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='ID Number'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='64040612381912'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='ID Expiration Date'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='07/10/2025'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
      </Grid>
      <Grid
        container
        width={700}
        justifyContent='space-between'
        wrap='wrap'
        marginBottom='32px'
      >
        <Grid
          item
          sm={12}
        >
          <Text
            title='Bank Information'
            fontWeight={700}
            color='primary.500'
            variant='text-lg'
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Bank'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='BCA'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title={`Bank Account Holder's Name`}
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='Ratna Sari'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          container
          minWidth='1050px !important'
          wrap='wrap'
        >
          <Grid
            item
            mb={2}
            mt={2}
            sm={4}
          >
            <Text
              title='Bank Account No'
              color='grey.400'
              fontWeight={500}
              mb={0.5}
            />
            <Text
              title='40061231231'
              color='grey.600'
              fontWeight={400}
            />
          </Grid>
          <Grid
            item
            mb={2}
            mt={2}
            sm={4}
          >
            <Text
              title='Bank Code'
              color='grey.400'
              fontWeight={500}
              mb={0.5}
            />
            <Text
              title='004'
              color='grey.600'
              fontWeight={400}
            />
          </Grid>
          <Grid
            item
            mb={2}
            mt={2}
            sm={4}
          >
            <Text
              title='Branch Code'
              color='grey.400'
              fontWeight={500}
              mb={0.5}
            />
            <Text
              title='014'
              color='grey.600'
              fontWeight={400}
            />
          </Grid>
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Branch Name'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='KCP kebayoran Baru'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
        <Grid
          item
          mb={2}
          mt={2}
          sm={6}
        >
          <Text
            title='Swift Code'
            color='grey.400'
            fontWeight={500}
            mb={0.5}
          />
          <Text
            title='CAD1-AS-BG-123'
            color='grey.600'
            fontWeight={400}
          />
        </Grid>
      </Grid>
    </>
  );
};

export default EmployeePersonalInformationDetail;